meta:
  version: 3
  flow: Chip
  substituting_steps:

    # Disable KLayout DRC
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # Disable KLayout antenna check
    #KLayout.Antenna: null
    #Checker.KLayoutAntenna: null

    # Disable KLayout density check
    #KLayout.Density: null
    #Checker.KLayoutDensity: null

    # Save time during development
    # Enable for sign-off
    #OpenROAD.IRDropReport: null
    #Magic.DRC: null
    #Checker.MagicDRC: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv
- dir::../src/chip_core.sv

# Enable plugin for better SystemVerilog support
# USE_SLANG: True
# SLANG_ARGUMENTS: ['--keep-hierarchy']

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# We need to add gf180mcu_fd_io__bi_24t
# due to the unused Y output for output only pads
IGNORE_DISCONNECTED_MODULES:
- gf180mcu_fd_io__bi_24t
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/Y
CLOCK_PERIOD: 40 # 25 MHz

# Fix hold violations
PL_RESIZER_HOLD_SLACK_MARGIN: 0.35
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.3

# Increase for more logic
# on your die
PL_TARGET_DENSITY_PCT: 35
GRT_ALLOW_CONGESTION: true

# Fix antenna violations after DRT
DRT_ANTENNA_REPAIR_ITERS: 10
DRT_ANTENNA_REPAIR_MARGIN: 10 # %

# PDN - Straps
PDN_VWIDTH: 5
PDN_HWIDTH: 5
PDN_VSPACING: 1
PDN_HSPACING: 1
PDN_VPITCH: 75
PDN_HPITCH: 75

# PDN - Core ring
PDN_CORE_RING: True
# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 25
PDN_CORE_RING_HWIDTH: 25
PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False
PDN_CORE_VERTICAL_LAYER: Metal2
PDN_CORE_HORIZONTAL_LAYER: Metal3

# Due to OpenROAD bug
# https://github.com/The-OpenROAD-Project/OpenROAD/issues/8229
#PL_TIME_DRIVEN: False
#PL_ROUTABILITY_DRIVEN: False

# Do not error on magic DRC violations
# Note: Passing magic DRC is not required for the submission.
# However, it is recommended to fix or carefully review all violations.
ERROR_ON_MAGIC_DRC: False

# Prevent false positive DRC errors in I/O cells
MAGIC_GDS_FLATGLOB:
# For contacts
- "*_CDNS_*"
# Foundry provided SRAMs
- "*$$*"
- "M1_N*"
- "M1_P*"
- "M2_M1*"
- "M3_M2*"
- "nmos_5p0*"
- "nmos_1p2*"
- "pmos_5p0*"
- "pmos_1p2*"
- "via1_*"
- "ypass_gate*"
- "G_ring_*"
# These additional cells must be flattened to get rid of 3.3V devices
# (DUALGATE drawn into high-level cells)
- "dcap_103*"
- "din_*"
- "mux821_*"
- "rdummy_*"
- "pmoscap_*"
- "xdec_*"
- "ypredec*"
- "xpredec*"
- "prexdec_*"
- "xdec8_*"
- "xdec16_*"
- "xdec32_*"
- "sa_*"

# Since we cannot meet the minimum density limit on Metal2,
# ignore active metal on previous and subsequent layers
# (DM.5_DM.7 and DM.4_DM.6). Dummy metal is moved to active
# metal during the precheck.
KLAYOUT_FILLER_OPTIONS:
  Metal2_ignore_active: true

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

MACROS:
  gf180mcu_ws_ip__id:
    gds:
      - dir::../ip/gf180mcu_ws_ip__id/gds/gf180mcu_ws_ip__id.gds
    lef:
      - dir::../ip/gf180mcu_ws_ip__id/lef/gf180mcu_ws_ip__id.lef
    vh:
      - dir::../ip/gf180mcu_ws_ip__id/vh/gf180mcu_ws_ip__id.v
    lib:
      "*":
        - dir::../ip/gf180mcu_ws_ip__id/lib/gf180mcu_ws_ip__id.lib
    instances:
      chip_id:
        location: [26, 26]
        orientation: N

  gf180mcu_ws_ip__logo:
    gds:
      - dir::../ip/gf180mcu_ws_ip__logo/gds/gf180mcu_ws_ip__logo.gds
    lef:
      - dir::../ip/gf180mcu_ws_ip__logo/lef/gf180mcu_ws_ip__logo.lef
    vh:
      - dir::../ip/gf180mcu_ws_ip__logo/vh/gf180mcu_ws_ip__logo.v
    lib:
      "*":
        - dir::../ip/gf180mcu_ws_ip__logo/lib/gf180mcu_ws_ip__logo.lib
    instances:
      wafer_space_logo:
        location: ["expr::$DIE_AREA[2] + -169.25", "expr::$DIE_AREA[3] + -169.25"]
        orientation: N

  gf180mcu_fd_ip_sram__sram512x8m8wm1:
    gds:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/gds/gf180mcu_fd_ip_sram__sram512x8m8wm1.gds
    lef:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lef/gf180mcu_fd_ip_sram__sram512x8m8wm1.lef
    vh:
      - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/verilog/gf180mcu_fd_ip_sram__sram512x8m8wm1__blackbox.v
    lib:
      "*_tt_025C_5v00":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__tt_025C_5v00.lib
      "*_ff_n40C_5v50":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__ff_n40C_5v50.lib
      "*_ss_125C_4v50":
        - pdk_dir::libs.ref/gf180mcu_fd_ip_sram/lib/gf180mcu_fd_ip_sram__sram512x8m8wm1__ss_125C_4v50.lib
    instances:
      # Make sure to specify the SRAMs in pdn_cfg.tcl
      i_chip_core.sram_0:
        location: [490, 500]
        orientation: N
      i_chip_core.sram_1:
        location: [970, 500]
        orientation: E

# This is an alternative method compared to
# specifying the power connections in the RTL
PDN_MACRO_CONNECTIONS:
- "i_chip_core.sram_0 VDD VSS VDD VSS"
- "i_chip_core.sram_1 VDD VSS VDD VSS"

# Halo size around macros while cutting rows.
# Workaround for: https://github.com/The-OpenROAD-Project/OpenROAD/issues/8868
FP_MACRO_HORIZONTAL_HALO: 10
FP_MACRO_VERTICAL_HALO: 10
PDN_HORIZONTAL_HALO: 5
PDN_VERTICAL_HALO: 5

PDN_CFG: dir::pdn_cfg.tcl
